<a href="https://colab.research.google.com/github/dev-SR/Deep-Learning/blob/main/01-pytorch-basics/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch

In [1]:
"""
cd .\101pytorch\
jupyter nbconvert --to markdown torch.ipynb --output README.md
"""
import torch
import numpy as np
import matplotlib.pyplot as plt

## Initialize tensors

In [7]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.rand(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.9650, 0.5336],
        [0.9020, 0.5464],
        [0.9453, 0.0591]])


In [10]:
x.shape

torch.Size([3, 2])

In [4]:
x = torch.empty(3,2) 
print(x)
y = torch.zeros_like(x)
y

tensor([[1.1515e-29, 4.5831e-41],
        [1.1515e-29, 4.5831e-41],
        [0.0000e+00, 0.0000e+00]])


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
x = torch.linspace(0,1,steps=5)
x

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [12]:
py_ndArr = [[1,2],
			[3,4],
			[5,6]]
x = torch.tensor(py_ndArr)
x

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Slicing Tensor

In [15]:
print(x)
print(x.size())
print(x[:,1]) # all row; 1th coloumn
print(x[0,:]) # 0th row, all columns

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


## 🚀Reshaping Tensor

In [19]:
print(x)
y = x.view(2,3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [20]:
y = x.view(6,-1) # 6 row; auto coloumn
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


## Tensor Operation

In [ ]:
x = torch.ones([3,2])
y = torch.ones([3,2])

z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
z = y.add(x)
z

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [ ]:
# modify inplace
z = y.add_(x)
print(z)
print(y)


tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


## Numpy/Python `<>` PyTorch

- PyTorch To `Numpy`

In [25]:
x.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

-  PyTorch To `python`

In [27]:
y = x[1,1]
print(y)
print(y.item())

r0 = x[0,:]
print(r0)
print(r0.tolist())

tensor(4)
4
tensor([1, 2])
[1, 2]


- Pytorch to Numpy to Python List

In [32]:
# Create a PyTorch tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Convert the tensor to a NumPy array
numpy_array = tensor.numpy()
# Convert the NumPy array to a Python list
python_list = numpy_array.tolist()
print(python_list) # Output: [[1, 2, 3], [4, 5, 6]]


[[1, 2, 3], [4, 5, 6]]


- Numpy to PyTorch

In [28]:
np.random.seed(0)
ar = np.random.randn(5)

print(ar)
ar_pt = torch.from_numpy(ar)
print(ar_pt)
print(type(ar),type(ar_pt))

[1.76405235 0.40015721 0.97873798 2.2408932  1.86755799]
tensor([1.7641, 0.4002, 0.9787, 2.2409, 1.8676], dtype=torch.float64)
<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [29]:
np.add(ar,1,out=ar)
print(ar)
# torch also gets updated
print(ar_pt)

[2.76405235 1.40015721 1.97873798 3.2408932  2.86755799]
tensor([2.7641, 1.4002, 1.9787, 3.2409, 2.8676], dtype=torch.float64)


- Tensor and Numpy benchmark:

In [30]:
%%time
for i in range(10):
	a = np.random.randn(10000,10000)
	b = np.random.randn(10000,10000)
	c = a*b

CPU times: user 1min 5s, sys: 5.19 s, total: 1min 10s
Wall time: 1min 11s


In [31]:

%%time
for i in range(10):
	a = torch.randn(10000,10000)
	b = torch.randn(10000,10000)
	c = a*b

CPU times: user 17.2 s, sys: 7.24 s, total: 24.5 s
Wall time: 23.8 s


## 🔥AutoGrad

Autograd is a key feature of PyTorch that provides **automatic differentiation for all operations on tensors**. It allows developers to easily compute gradients of tensors with respect to other tensors. Autograd tracks all operations that are performed on tensors, creates a computation graph, and then uses the chain rule of differentiation to compute gradients. This feature is essential for training deep neural networks, as it allows us to efficiently calculate the gradients needed for optimization algorithms like stochastic gradient descent.

For the equation of $$z = 2x^{2} + 3y^{3}$$

The derivative of z with respect to x is:

$$\frac{\partial z}{\partial x} = 4x$$

The derivative of z with respect to y is:

$$\frac{\partial z}{\partial y} = 9y^{2}$$

Therefore, The derivative of $z=2x^2+3y^3$ with respect to $x$ evaluated at $x=2$ is:
$$\frac{\partial z}{\partial x}\bigg|_{x=2} = 4(2) = 8$$

And the derivative of $z$ with respect to $y$ evaluated at $y=1$ is:
$$\frac{\partial z}{\partial y}\bigg|_{y=1} = 9(1)^2 = 9$$

In [35]:
import torch

# Define x and y as tensors with requires_grad=True
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(1.0, requires_grad=True)

# Define z as a function of x and y
z = 2*x**2 + 3*y**3

# Compute the gradients of z with respect to x and y
z.backward()

# Print the gradients
print('Gradient of z with respect to x:', x.grad)
print('Gradient of z with respect to y:', y.grad)


Gradient of z with respect to x: tensor(8.)
Gradient of z with respect to y: tensor(9.)


Building autograd feature from scratch : [building micrograd](https://www.youtube.com/watch?v=VMj-3S1tku0)